import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar/Navbar'
import Banner from '@/components/Banner/Banner'
import SimpleBanner from '@/components/SimpleBanner/SimpleBanner'
import WorkoutBanner from '@/components/WorkoutBanner/WorkoutBanner'
import Card from '@/components/Card/Card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <Banner></Banner>
        <SimpleBanner></SimpleBanner>
        <Card></Card>
        <WorkoutBanner></WorkoutBanner>
      </Navbar>

    </>
  )
}
